name: ci

on:
  push:

jobs:
  docker:
    runs-on: depot-ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: depot/setup-action@v1
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: depot/build-push-action@v1
        with:
          build-args: |
            PGBOUNCER_CHECKSUM=sha256:da72a3aba13072876d055a3e58dd4aba4a5de4ed6148e73033185245598fd3e0
            PGBOUNCER_TAG=1_24_1
            PGBOUNCER_VERSION=1.24.1
          context: .
          platforms: linux/amd64,linux/arm64
          project: ${{ secrets.DEPOT_PROJECT_ID }}
          push: true
          tags: ghcr.io/viaeurope/pgbouncer:1.24.1
