name: ci


on:
  push:
    branches:
      - '**'

jobs:
  docker:
    runs-on: depot-ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: depot/setup-action@v1
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Load build args from .env
        run: |
          grep -E '^(PGBOUNCER_TAG|PGBOUNCER_VERSION|PGBOUNCER_CHECKSUM)=' .env >> "$GITHUB_ENV"
      - name: Build Docker image (no push on non-main)
        uses: depot/build-push-action@v1
        with:
          build-args: |
            PGBOUNCER_CHECKSUM=${{ env.PGBOUNCER_CHECKSUM }}
            PGBOUNCER_TAG=${{ env.PGBOUNCER_TAG }}
            PGBOUNCER_VERSION=${{ env.PGBOUNCER_VERSION }}
          context: .
          platforms: linux/amd64,linux/arm64
          project: ${{ secrets.DEPOT_PROJECT_ID }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ github.ref == 'refs/heads/main' && format('ghcr.io/viaeurope/pgbouncer:{0}', env.PGBOUNCER_VERSION) || '' }}
